# -*- coding: utf-8 -*-
"""사전 v2 · 자문 항목(한글) → 영문 필드명 사전.

배치표의 항목명을 그대로 키로 쓴다. 같은 뜻의 항목은 같은 이름으로 합쳐진다(예: 생체검사 시행 부위 / 실시 부위).
여기에 없는 항목은 build_spec_v2.py 가 임시 이름(item_NNN)을 붙이고 보고서에 남긴다.
"""

FIELD_NAMES = {
    # ---- 생활습관·전신상태
    "흡연력 여부": "smoking_history_yn", "현재 흡연 여부": "current_smoker_yn", "1일 평균 흡연량": "cigarettes_per_day",
    "총 흡연기간": "smoking_years", "마지막 금연 시작 연도": "quit_smoking_year", "활동능력(ECOG) 점수": "ecog_score",
    "총 운동기간": "exercise_duration_months", "주 평균 운동횟수": "exercise_sessions_per_week", "1회당 운동시간": "exercise_minutes_per_session",
    "총 음주기간": "drinking_years", "월평균 음주횟수": "drinking_days_per_month", "평균 음주량": "alcohol_amount_per_occasion",
    "알코올 사용장애 선별점수(AUDIT)": "audit_score",
    # ---- 과거력·가족력
    "과거 병력 여부": "hx_any_yn", "과거 기타 호흡기질환 여부": "hx_other_respiratory_yn", "과거 기타 호흡기질환 내용": "hx_other_respiratory_detail",
    "과거 심장질환 여부": "hx_heart_disease_yn", "과거 결핵 여부": "hx_tuberculosis_yn", "과거 암 병력 여부": "hx_cancer_yn",
    "과거 암 병력의 암종": "hx_cancer_type", "과거 고혈압 여부": "hx_hypertension_yn", "과거 당뇨병 여부": "hx_diabetes_yn",
    "과거 간질환 여부": "hx_liver_disease_yn", "과거 복부 수술 여부": "hx_abdominal_surgery_yn", "과거 복부 수술 종류": "hx_abdominal_surgery_type",
    "과거 대장 질환 여부": "hx_colorectal_disease_yn", "과거 신장 질환 여부": "hx_kidney_disease_yn", "유전성 대장암 여부": "hereditary_crc_yn",
    "과거 제2형 당뇨병 여부": "hx_t2dm_yn", "과거 이상지질혈증 여부": "hx_dyslipidemia_yn", "과거 심혈관질환 여부": "hx_cardiovascular_yn",
    "과거 갑상선기능저하증 여부": "hx_hypothyroidism_yn", "과거 만성 바이러스간염(B형·C형) 여부": "hx_viral_hepatitis_yn",
    "과거 비만대사수술 여부": "hx_bariatric_surgery_yn", "과거 뇌혈관질환 여부": "hx_cerebrovascular_yn", "과거 만성콩팥병 여부": "hx_ckd_yn",
    "과거 췌장질환 여부": "hx_pancreatic_disease_yn", "B형간염 감염 상태": "hbv_status", "C형간염 감염 상태": "hcv_status", "HIV 감염 상태": "hiv_status",
    "가족력 여부": "family_history_yn", "가족력 대상자와의 관계": "family_relation", "가족의 암 병력 여부": "family_cancer_yn",
    "가족의 암 병력 암종": "family_cancer_type", "가족의 간질환 병력 여부": "family_liver_disease_yn", "당뇨병 가족력 여부": "family_diabetes_yn",
    # ---- 진단·코호트
    "진단정보 등록일": "diagnosis_registered_date", "진단명": "diagnosis_name", "세부 진단명": "diagnosis_subtype",
    "최초 림프종 진단일": "first_diagnosis_date", "진단 상태": "diagnosis_status", "림프종 대분류": "lymphoma_category",
    "종양 세포 계열": "cell_lineage", "WHO/ICC 기준 조직학적 아형": "histologic_subtype", "당뇨병 유형": "diabetes_type",
    "당뇨병 최초 진단 시 나이": "age_at_diagnosis", "당뇨병 유병 기간": "disease_duration_years", "임신성 당뇨병 해당 여부": "gestational_diabetes_yn",
    "MASLD/MASH 진단 근거 기준": "masld_diagnosis_basis", "최종 추적 시 질환 상태": "last_disease_status",
    "최종 추적관찰일": "last_followup_date", "최종 추적 시 생존 상태": "last_vital_status",
    # ---- 병기
    "초진 시 임상 병기": "initial_clinical_stage", "4기 진단일(수술 환자는 재발일)": "stage_iv_diagnosis_date", "폐 종양 원발 부위": "primary_site",
    "수술 전 검사 결과에 따른 임상 TNM 병기값": "clinical_tnm", "임상 종양 특성": "clinical_tumor_feature",
    "수술 후 외과 병리 기록지의 TNM 병기값": "pathologic_tnm", "영상 판독상 원격 전이 여부": "imaging_distant_metastasis_yn",
    "원격 전이 진단일": "distant_metastasis_date", "원격 전이 부위": "distant_metastasis_site", "복강내 원격전이 부위": "intraabdominal_metastasis_site",
    "원발종양 편측성": "primary_sidedness", "수술치료 후 평가 내용": "post_surgery_assessment", "복막암지수(PCI)": "pci_score",
    "병기 평가일": "staging_date", "병기 분류체계": "staging_system", "Ann Arbor/Lugano 병기": "stage_group", "병기 수식자": "stage_modifier",
    "병기 결정 방법": "staging_method", "림프종 원발 침범 부위": "primary_involved_site", "침범 림프절 영역 수": "nodal_regions_involved",
    "결절외 침범 여부": "extranodal_yn", "침범 결절외 장기 수": "extranodal_sites_count", "결절외 침범 부위": "extranodal_sites",
    "비장 침범 여부": "spleen_involvement_yn", "골수 침범 여부": "bone_marrow_involvement_yn", "골수 내 림프종 침범 비율": "bone_marrow_involvement_percent",
    "중추신경계 침범 여부": "cns_involvement_yn", "Bulky disease 여부": "bulky_disease_yn", "Bulky disease 판정에 적용한 최대 직경 기준(cm)": "bulky_threshold_cm",
    "기준 시점의 가장 큰 병변 장경(cm)": "largest_lesion_diameter_cm", "B 증상 여부": "b_symptoms_yn", "원인불명 발열 여부": "fever_yn",
    "야간 발한 여부": "night_sweats_yn", "최근 6개월 체중감소율": "weight_loss_percent_6m",
    "고등급 조직학적 전환 여부": "transformation_yn", "조직학적 전환 확정일": "transformation_date",
    "전환 전 림프종 아형": "transformation_from_subtype", "전환 후 림프종 아형": "transformation_to_subtype",
    # ---- 병리
    "면역조직화학병리 검사": "ihc_test", "분자병리 검사": "molecular_pathology_test", "생체검사 시행 방법": "biopsy_method", "생체검사 방법": "biopsy_method",
    "생체검사 대상 부위 or 검체": "biopsy_site", "생체검사 실시 부위 or 검체": "biopsy_site", "생체검사 시행 부위": "biopsy_site", "생체검사 부위": "biopsy_site",
    "생체검사 시행 폐 상세 위치": "biopsy_site_detail", "생체검사 결장 종양 세부위치": "biopsy_site_detail", "생체검사 직장 세부 부위 상세": "biopsy_rectum_site_detail",
    "생체검사 부위 편측성": "biopsy_laterality", "생체검사 검체 적절성 결과": "biopsy_adequacy", "간 생체검사 검체 적정성": "biopsy_adequacy",
    "수술 후 외과병리 조직 채취 부위": "surgical_specimen_site", "수술 후 외과병리 조직 채취부위": "surgical_specimen_site",
    "수술 후 병리 조직 채취 부위 편측성": "surgical_specimen_laterality", "수술 후 외과병리 종양 위치": "surgical_tumor_site",
    "병리검사에서 확인된 종양 개수": "tumor_count", "생체검사에 따른 조직학적 진단명": "biopsy_histologic_diagnosis",
    "생체검사 조직학적 분화도": "biopsy_differentiation", "수술 후 외과병리를 통해 확인된 조직학적 진단명": "surgical_histologic_diagnosis",
    "수술 후 외과병리를 통해 확인된 조직학적 등급": "surgical_histologic_grade", "원발 조직형 진단명": "primary_histology",
    "폐선암 우세 조직아형": "adenocarcinoma_predominant_subtype", "종양 가로 크기": "tumor_size_width_cm", "종양 세로 크기": "tumor_size_length_cm",
    "종양 높이": "tumor_size_height_cm", "수술 후 병리 종양 최대 직경": "pathologic_tumor_max_diameter_cm", "기강내 종양전파(STAS) 여부": "stas_yn",
    "장측흉막침범(VPI) 정도": "vpi_grade", "폐쇄후 폐렴 or 무기폐 동반 여부": "obstructive_pneumonia_atelectasis_yn",
    "절제된 감시림프절 개수": "sentinel_nodes_examined", "침윤된 감시림프절 개수": "sentinel_nodes_positive",
    "절제된 림프절 개수": "lymph_nodes_examined", "침윤된 림프절 개수": "lymph_nodes_positive", "미세석회화 여부": "microcalcification_yn",
    "관상피내암(DCIS) 핵등급": "dcis_nuclear_grade", "상피내암 동반 여부": "in_situ_component_yn", "기질 종양침윤림프구(TIL) 비율": "til_percent",
    "염증성 유방암 해당 여부": "inflammatory_breast_cancer_yn", "종양의 림프관·혈관 침윤 여부": "lymphovascular_invasion_yn",
    "수술절제면 암조직 잔존 상태": "resection_margin_status", "잔존종양(Residual Tumor) 분류": "residual_tumor_r_class",
    "Gross type 분류 명칭": "gross_type", "복강세척 세포검사 결과": "peritoneal_cytology_result", "종양 내 T세포 침윤 정량화 면역점수": "immunoscore",
    "종양침착(tumor deposits, N1c) 여부": "tumor_deposits_yn", "종양출아등급(tumor budding)": "tumor_budding_grade", "근치도(절제 정도)": "resection_completeness",
    "림프관 침윤 여부": "lymphatic_invasion_yn", "혈관 침윤 여부": "vascular_invasion_yn", "신경주위 침윤 여부": "perineural_invasion_yn",
    "종양 침윤 깊이 정도": "invasion_depth", "수술후 외과병리 검사에서 확인된 radial 또는 circumferential margin 의 상태": "crm_status",
    "전직장간막절제술(TME) 육안적 완전도": "tme_quality",
    "간실질 섬유화 등급명": "liver_fibrosis_grade_name", "간 생체검사 지방증 등급": "steatosis_grade", "간 생체검사 소엽 염증 등급": "lobular_inflammation_grade",
    "간세포 풍선변성 등급": "ballooning_grade", "섬유화 병기(NASH CRN)": "fibrosis_stage", "NAS 총점": "nas_score",
    # ---- 바이오마커
    "유전자 돌연변이검사 방법": "mutation_test_method", "돌연변이검사 시행 유전자 종류": "mutation_test_gene", "유전자 돌연변이검사 결과": "mutation_test_result",
    "Reference Sequence 값": "reference_sequence", "DNA 변이 정보 A 값": "dna_variant_a", "DNA 변이 정보 B 값": "dna_variant_b", "DNA 변이 정보 C 값": "dna_variant_c",
    "아미노산 변이 정보 A": "protein_variant_a", "아미노산 변이 정보 B": "protein_variant_b", "아미노산 변이 정보 C": "protein_variant_c",
    "예후예측 유전자 발현검사 종류": "prognostic_gene_assay_type", "예후예측 유전자 발현검사 결과": "prognostic_gene_assay_result",
    "생식세포 변이검사 방법": "germline_test_method", "생식세포 변이검사 유전자 종류": "germline_test_gene", "생식세포 변이검사 결과 내용": "germline_test_result",
    "Pathogenic 검출 여부": "pathogenic_variant_yn", "Unclassified Variant 검출 여부": "vus_yn", "PAM50 재발위험(ROR) 점수": "pam50_ror_score",
    "Oncotype DX 재발점수": "oncotype_rs", "Oncotype DX 위험군": "oncotype_risk_group", "MammaPrint 재발위험 판정": "mammaprint_result",
    "유방암 분자아형": "molecular_subtype",
    "CD3 검사 결과": "cd3_result", "CD5 검사 결과": "cd5_result", "CD10 검사 결과": "cd10_result", "CD15 검사 결과": "cd15_result",
    "CD19 검사 결과": "cd19_result", "CD20 검사 결과": "cd20_result", "CD22 검사 결과": "cd22_result", "CD23 검사 결과": "cd23_result",
    "CD30 검사 결과": "cd30_result", "CD79a 검사 결과": "cd79a_result", "PAX5 검사 결과": "pax5_result",
    "BCL2 단백 발현 결과와 양성률": "bcl2_protein_result", "BCL6 단백 발현 결과와 양성률": "bcl6_protein_result", "MUM1/IRF4 발현 결과와 양성률": "mum1_result",
    "MYC 단백 발현 결과와 양성률": "myc_protein_result", "Cyclin D1 발현 결과": "cyclin_d1_result", "SOX11 발현 결과": "sox11_result",
    "ALK 발현 또는 재배열 검사 결과": "alk_result", "PD-L1 발현 결과 및 평가법": "pdl1_result", "Ki-67 증식지수": "ki67_percent",
    "EBV EBER 검사 결과": "ebv_eber_result", "DLBCL 세포기원 분류": "dlbcl_cell_of_origin", "MYC/BCL2 이중발현 여부": "double_expressor_yn",
    "유세포검사 면역표현형 요약": "flow_cytometry_summary", "분자·세포유전검사 시행일": "molecular_test_date", "분자·세포유전검사 방법": "molecular_test_method",
    "MYC 재배열 검사 결과": "myc_rearrangement_result", "BCL2 재배열 검사 결과": "bcl2_rearrangement_result", "BCL6 재배열 검사 결과": "bcl6_rearrangement_result",
    "Double-hit/Triple-hit 상태": "double_hit_status", "t(14;18) 전좌 검사 결과": "t14_18_result", "t(11;14) 전좌 검사 결과": "t11_14_result",
    "TP53 변이, 17p 결실 또는 비정상 p53 발현 결과": "tp53_abnormality_result", "Complex karyotype 여부": "complex_karyotype_yn",
    "IG/TCR 클론성 검사 결과": "ig_tcr_clonality_result", "유세포, PCR 또는 NGS 기반 미세잔존질환(MRD) 결과": "mrd_result", "순환종양DNA(ctDNA) 결과": "ctdna_result",
    "췌도 자가항체(GAD 항체) 결과": "gad_antibody_result",
    # ---- 영상·기능검사
    "기관지내시경 검사 시행일": "bronchoscopy_date", "기관지내시경 검사명": "bronchoscopy_name", "영상검사명": "imaging_name",
    "영상검사 결과 진단적 분류(Diagnostic Classification)": "imaging_diagnostic_classification", "영상검사상 폐 종양 최대 직경": "imaging_tumor_max_diameter_cm",
    "고형성분 비율(CTR)": "ctr_ratio", "폐결절 방사선학적 유형": "nodule_radiologic_type", "폐기능검사 항목": "pft_item", "폐기능검사 결과값": "pft_value",
    "영상검사 결과 소견": "imaging_findings_text", "유방촬영술상 유방 밀도": "mammographic_density", "유방촬영술상 미세석회화 여부": "mammographic_microcalcification_yn",
    "Rigid sigmoidoscopy 또는 MRI에서 측정된 직장암 위치 값": "rectal_tumor_height_cm", "MRI 판독 결과 T3 이상에서 종양침윤 최대깊이 값(mm)": "mri_invasion_depth_mm",
    "MRI 판독 결과 T4B에서 침윤된 장기 부위": "mri_t4b_invaded_organ", "MRI 판독 결과 종양과 전방복막의 관계": "mri_anterior_peritoneal_relation",
    "MRI 판독 결과 종양의 하부연과 항문연 사이의 거리 값(cm)": "mri_distance_anal_verge_cm",
    "MRI 판독 결과 종양의 하부연과 항문직장경계부 사이의 거리 값(cm)": "mri_distance_anorectal_junction_cm",
    "MRI 판독 결과 종양의 환상 침범 범위(Circumferential tumor location)": "mri_circumferential_extent",
    "MRI 판독 결과 직장간막근막에서 종양까지의 최단거리 값(mm)": "mri_mrf_distance_mm", "MRI 판독 결과 장벽외 혈관침윤(EMVI) 여부": "mri_emvi_yn",
    "MRI 판독 결과 직장 간내 림프절전이 여부": "mri_mesorectal_node_yn", "MRI 판독 결과 직장 간외 림프절전이 여부": "mri_extramesorectal_node_yn",
    "MRI 판독 결과 종양의 환상 위치": "mri_circumferential_location", "MRI 판독 결과 종양반응등급(Radiologic tumor regression grade)": "mri_tumor_regression_grade",
    "PET 최고 SUVmax": "pet_suvmax", "대사종양용적(MTV)": "metabolic_tumor_volume_ml", "총병변당분해(TLG)": "total_lesion_glycolysis", "종격동 종괴비(MMR)": "mediastinal_mass_ratio",
    "간 영상·탄성도 검사 시행일": "elastography_date", "MRI-PDFF 간지방분율": "mri_pdff_percent", "MRE 간 경직도": "mre_kpa",
    "FibroScan 감쇠계수(CAP)": "cap_db_m", "FibroScan 간 경직도(LSM)": "lsm_kpa", "간정맥압력차(HVPG)": "hvpg_mmhg", "비장 경직도": "spleen_stiffness_kpa",
    "감각신경 전도속도(sensory nerve conduction velocity)": "sensory_ncv_m_s", "진동감각역치(VPT)": "vpt_volt", "발목-상완 지수(ABI)": "abi",
    "최대교정시력(BCVA)": "bcva", "중심 황반 두께(OCT)": "central_macular_thickness_um",
    # ---- 검사(혈액)
    "예후 판단척도 산출 시 사용된 혈액검사 시행일": "score_input_lab_date", "예후 판단척도 산출 시 사용된 혈액검사명": "score_input_lab_name",
    "예후 판단척도 산출 시 사용된 혈액검사 결과값": "score_input_lab_value", "대사이상지방간 예후 판단척도 종류": "prognostic_score_type",
    "대사이상지방간 예후 판단척도 산식에 따른 산출 결과 값": "prognostic_score_value", "ELF 섬유화 점수": "elf_score", "FIB-4 지수": "fib4_index",
    "NAFLD 섬유화 점수(NFS)": "nfs_score", "APRI 점수": "apri_score", "혈청 PRO-C3": "pro_c3_ng_ml", "NIS4 점수": "nis4_score",
    "요 알부민/크레아티닌 비(UACR)": "uacr_mg_g", "CGM 목표범위 내 시간 비율(TIR)": "cgm_tir_percent", "CGM 고혈당 시간 비율(TAR)": "cgm_tar_percent",
    "CGM 저혈당 시간 비율(TBR)": "cgm_tbr_percent", "CGM 평균 혈당": "cgm_mean_glucose_mg_dl", "CGM tight range(70-140 mg/dL) 체류 시간 비율": "cgm_titr_percent",
    "공복 혈장 포도당(FPG) 측정값": "fpg_mg_dl", "공복 인슐린": "fasting_insulin_uiu_ml", "식후 혈당 농도 측정값": "postprandial_glucose_mg_dl",
    "혈당 변동성 지표": "glycemic_variability", "경구당부하검사 2시간 혈당값": "ogtt_2h_glucose_mg_dl", "임의 시점에 측정한 무작위 혈당값": "random_glucose_mg_dl",
    "당화혈색소(HbA1c) 값": "hba1c_percent", "C-펩타이드 농도값": "c_peptide_ng_ml", "인슐린 저항성 지수(HOMA-IR)": "homa_ir", "베타세포 기능 지수(HOMA-beta)": "homa_beta",
    "프룩토사민값": "fructosamine_umol_l",
    # ---- 치료
    "방사선치료 처방일": "rt_prescription_date", "방사선치료명": "rt_name", "방사선치료 목적": "rt_purpose", "방사선치료 부위": "rt_site",
    "방사선 1회 선량 값(Gy)": "rt_dose_per_fraction_gy", "방사선 부위별 시행 횟수": "rt_fractions", "방사선치료 총 선량 값(Gy)": "rt_total_dose_gy",
    "방사선 부위별 총 선량 값(Gy)": "rt_total_dose_gy", "방사선치료 시행 여부": "rt_yn",
    "수술 시행일": "surgery_date", "수술명": "surgery_name", "수술 목적": "surgery_purpose", "수술 부위": "surgery_site", "수술 방법": "surgery_approach",
    "수술 시 확인한 종양 위치": "surgery_tumor_location", "재건·성형술 분류": "reconstruction_type", "간이식 수술 시행일": "surgery_date", "간이식 수술명": "surgery_name",
    "수술 전 폐색치료 시행 여부": "preop_obstruction_treatment_yn", "수술 시 장루형성 여부": "stoma_yn", "수술 시 장루형성 이유": "stoma_reason",
    "IMA (Inferior mesenteric artery) ligation 위치": "ima_ligation_level", "비장굴곡 가동화 여부": "splenic_flexure_mobilization_yn",
    "문합 방법": "anastomosis_method", "문합 방법 세부 내용": "anastomosis_detail", "문합부 위치 값": "anastomosis_height_cm",
    "수술 중 추정실혈량 구분": "ebl_category", "수술 중 추정실혈량 값": "ebl_ml", "장루 복원 수술 시행일": "stoma_reversal_date",
    "장루 복원 수술명": "stoma_reversal_name", "장루 복원 수술 위치": "stoma_reversal_site", "완전감축점수(CC score)": "cc_score",
    "비수술적 경과관찰(watch-and-wait) 상태": "watch_and_wait_status", "온열복강내항암화학요법(HIPEC) 시행 여부": "hipec_yn",
    "비개복수술 시행 중 개복수술로 전환 여부": "conversion_to_open_yn", "비개복수술 시행 중 개복수술로 전환되었을 때 사유": "conversion_reason",
    "이전 전신치료 line 수": "prior_lines_count", "현재 치료 line 번호": "line_number", "항암요법 레지멘명": "regimen_name", "투여 사이클 수": "cycles_count",
    "Anti-CD20 치료 이력 여부": "anti_cd20_yn", "Anthracycline 치료 이력 여부": "anthracycline_yn", "BTK 억제제 치료 이력 여부": "btk_inhibitor_yn",
    "면역관문억제제 치료 이력 여부": "checkpoint_inhibitor_yn", "조혈모세포이식 시행 여부": "sct_yn", "조혈모세포 주입 또는 이식일": "sct_date",
    "조혈모세포이식 유형": "sct_type", "CAR-T 세포치료 시행 여부": "car_t_yn", "CAR-T 세포 주입일": "car_t_infusion_date", "CAR-T 표적 항원": "car_t_target",
    "백혈구성분채집일": "apheresis_date", "림프구감소 전처치 시작일": "lymphodepletion_start_date",
    "인슐린 사용 여부": "insulin_use_yn", "1일 총 인슐린 투여량": "total_daily_insulin_units", "메트포르민 사용 여부": "metformin_use_yn",
    "SGLT2 억제제 사용 여부": "sglt2i_use_yn", "GLP-1 수용체 작용제 사용 여부": "glp1ra_use_yn", "DPP-4 억제제 사용 여부": "dpp4i_use_yn",
    "연속혈당측정기(CGM) 사용 여부": "cgm_use_yn", "인슐린 펌프/폐회로 시스템 사용 여부": "insulin_pump_yn",
    # ---- 경과·반응
    "사망일": "death_date", "사망 원인": "death_cause", "입/퇴원일": "admission_discharge_date", "퇴원 시 환자 상태": "discharge_status",
    "암 재발 진단일": "recurrence_date", "완전 또는 부분관해 후 림프종 재발 확인일": "recurrence_date", "암 재발 부위": "recurrence_site", "재발 부위": "recurrence_site",
    "선행항암 후 병리학적 완전관해 여부": "pcr_yn", "병리학적 완전관해(pCR) 여부": "pcr_yn", "선행치료 후 잔존종양부담(RCB) 등급": "rcb_class",
    "신보조직장점수(NAR score)": "nar_score", "임상적 완전관해(cCR) 판정 상태": "ccr_status", "장천공 여부": "bowel_perforation_yn",
    "장폐색 여부": "bowel_obstruction_yn", "합병증 치료방법": "complication_treatment",
    "측정가능 병변 존재 여부": "measurable_disease_yn", "표적 병변 개수": "target_lesions_count", "표적 병변 직경곱 합(SPD)": "spd_mm2",
    "질환 경과 상태": "disease_status", "일차 치료 불응 여부": "primary_refractory_yn", "질환 반응평가 기준일": "response_assessment_date",
    "반응평가 시점": "response_timepoint", "적용 반응평가 기준": "response_criteria", "반응평가 검사 방법": "response_method",
    "Deauville 5점 척도": "deauville_score", "해부학적 반응": "anatomic_response", "대사 반응": "metabolic_response", "최적 종합반응": "best_overall_response",
    "기저 골수 침범이 있었던 환자의 골수 반응 결과": "bone_marrow_response",
    "예후지수 산정 기준일": "prognostic_index_date", "IPI 총점": "ipi_score", "IPI 위험군": "ipi_risk_group", "연령보정 IPI(aaIPI) 총점": "aaipi_score",
    "NCCN-IPI 총점": "nccn_ipi_score", "FLIPI 총점": "flipi_score", "FLIPI2 총점": "flipi2_score", "MIPI 점수": "mipi_score", "MIPI-c 위험군": "mipi_c_risk_group",
    "호지킨림프종 IPS 총점": "ips_score", "말초T세포림프종 PIT 총점": "pit_score", "GELF 고종양부담 충족 여부": "gelf_high_burden_yn",
    "MELD(Model for End-stage Liver Disease) 점수": "meld_score", "Child-Pugh(간기능 중증도) 등급": "child_pugh_class", "MASH 소실 여부": "mash_resolution_yn",
    "섬유화 1단계 이상 호전 여부": "fibrosis_improvement_yn", "간경변증 동반 여부": "cirrhosis_yn",
    "간부전 비대상성 사건(복수·정맥류출혈·간성뇌증 등) 발생 여부": "decompensation_event_yn", "문맥압항진증 여부": "portal_hypertension_yn",
    "내시경으로 확인된 식도정맥류 여부": "esophageal_varices_yn", "간세포암(HCC) 발생 여부": "hcc_yn",
    "HbA1c 7% 미만 목표 달성 여부": "hba1c_target_met_yn", "중증 저혈당 발생 횟수": "severe_hypoglycemia_count", "저혈당 무감지증 여부": "hypoglycemia_unawareness_yn",
    "만성콩팥병(CKD) 병기": "ckd_stage", "당뇨병성 케톤산증(DKA) 발생 여부": "dka_yn", "당뇨병성 망막병증 중증도 등급": "retinopathy_severity",
    "당뇨병성 황반부종 여부": "macular_edema_yn", "당뇨병성 말초신경병증 여부": "peripheral_neuropathy_yn", "당뇨병성 족부궤양 여부": "foot_ulcer_yn",
    "족부궤양 Wagner 등급": "wagner_grade", "심장 자율신경병증 여부": "cardiac_autonomic_neuropathy_yn", "샤르코 관절병증(Charcot foot) 여부": "charcot_foot_yn",
    # ---- 생식·산과 (유방)
    "결혼 여부": "married_yn", "결혼상태 상세 구분": "marital_status_detail", "초경 만 나이": "menarche_age", "가임력 보존 치료 시행 여부": "fertility_preservation_yn",
    "가임력 보존 치료 종류": "fertility_preservation_type", "가임력 보존 치료 기타 내용": "fertility_preservation_other", "출산 경험 여부": "parity_yn",
    "첫 출산 만 나이": "first_birth_age", "임신 방법": "conception_method", "임신 결과": "pregnancy_outcome", "출산한 자녀 수": "number_of_children",
    "모유수유 경험 여부": "breastfeeding_yn", "폐경 여부": "menopause_yn", "폐경 만 나이": "menopause_age", "폐경 후 호르몬 대체요법(HRT) 시행 여부": "hrt_yn",
    "호르몬 대체요법(HRT) 시행 기간": "hrt_duration_months", "유방암 진단 시 임신 여부": "pregnant_at_diagnosis_yn", "출산 후 1년 이내 진단 여부": "postpartum_diagnosis_yn",
    "진단 시점 폐경 상태": "menopausal_status_at_diagnosis", "항암 종료 1년 시점 월경 재개 여부": "menses_resumed_1y_yn", "항암 치료 후 첫 월경일": "first_menses_after_chemo_date",
    "항암 치료 후 월경 규칙성": "menses_regularity_after_chemo", "치료 후 임신 시도 여부": "pregnancy_attempt_yn", "치료 후 임신 시도 시작일": "pregnancy_attempt_start_date",
    "치료 후 임신 성공 여부": "pregnancy_success_yn", "치료 후 임신에서의 분만 시행 여부": "delivery_after_treatment_yn",
}

# 항목명에서 단위를 읽지 못할 때 쓰는 단위 사전 (필드명 기준)
UNITS = {
    "cigarettes_per_day": "{개비}/d", "smoking_years": "a", "drinking_years": "a", "exercise_duration_months": "mo", "exercise_minutes_per_session": "min",
    "tumor_size_width_cm": "cm", "tumor_size_length_cm": "cm", "tumor_size_height_cm": "cm", "pathologic_tumor_max_diameter_cm": "cm", "imaging_tumor_max_diameter_cm": "cm",
    "til_percent": "%", "ki67_percent": "%", "bone_marrow_involvement_percent": "%", "weight_loss_percent_6m": "%", "ctr_ratio": "1",
    "rt_dose_per_fraction_gy": "Gy", "rt_total_dose_gy": "Gy", "ebl_ml": "mL", "anastomosis_height_cm": "cm", "rectal_tumor_height_cm": "cm",
    "mri_pdff_percent": "%", "mre_kpa": "kPa", "cap_db_m": "dB/m", "lsm_kpa": "kPa", "hvpg_mmHg": "mm[Hg]", "hvpg_mmhg": "mm[Hg]", "spleen_stiffness_kpa": "kPa",
    "sensory_ncv_m_s": "m/s", "vpt_volt": "V", "central_macular_thickness_um": "um", "pro_c3_ng_ml": "ng/mL", "uacr_mg_g": "mg/g",
    "cgm_tir_percent": "%", "cgm_tar_percent": "%", "cgm_tbr_percent": "%", "cgm_titr_percent": "%", "cgm_mean_glucose_mg_dl": "mg/dL",
    "fpg_mg_dl": "mg/dL", "fasting_insulin_uiu_ml": "u[IU]/mL", "postprandial_glucose_mg_dl": "mg/dL", "ogtt_2h_glucose_mg_dl": "mg/dL",
    "random_glucose_mg_dl": "mg/dL", "hba1c_percent": "%", "c_peptide_ng_ml": "ng/mL", "fructosamine_umol_l": "umol/L", "total_daily_insulin_units": "[IU]/d",
    "metabolic_tumor_volume_ml": "mL", "spd_mm2": "mm2", "hrt_duration_months": "mo", "largest_lesion_diameter_cm": "cm", "bulky_threshold_cm": "cm",
    "mri_invasion_depth_mm": "mm", "mri_distance_anal_verge_cm": "cm", "mri_distance_anorectal_junction_cm": "cm", "mri_mrf_distance_mm": "mm",
}

# 필드별 코드표 지정 (배치표의 코드표 열이 비었거나 여러 개일 때 우선)
CODELIST_OVERRIDE = {
    "initial_clinical_stage": "STAGE_GROUP_AJCC8", "stage_group": "STAGE_LUGANO", "staging_system": "STAGE_SYSTEM", "stage_modifier": "STAGE_MODIFIER",
    "fibrosis_stage": "FIBROSIS_STAGE", "steatosis_grade": "NAS_STEATOSIS", "child_pugh_class": "CHILD_PUGH", "ckd_stage": "CKD_STAGE",
    "retinopathy_severity": "DR_SEVERITY", "wagner_grade": "WAGNER", "diabetes_type": "DM_TYPE", "sct_type": "SCT_TYPE",
    "response_criteria": "RESPONSE_CRITERIA", "best_overall_response": "RESPONSE", "anatomic_response": "RESPONSE", "metabolic_response": "RESPONSE",
    "bone_marrow_response": "RESPONSE", "deauville_score": "DEAUVILLE", "rcb_class": "RCB_CLASS", "family_relation": "FAMILY_RELATION",
    "discharge_status": "DISCHARGE_STATUS", "surgery_purpose": "SURG_PURPOSE", "surgery_approach": "SURG_APPROACH", "rt_purpose": "RT_PURPOSE",
    "mammographic_density": "BIRADS_DENSITY", "ipi_risk_group": "RISK_GROUP", "mipi_c_risk_group": "RISK_GROUP", "oncotype_risk_group": "RISK_GROUP",
    "ecog_score": "ECOG", "gestational_diabetes_yn": "YN", "hvpg_mmhg": None, "clinical_tnm": None, "pathologic_tnm": None, "diagnosis_name": None, "diagnosis_subtype": "CL_DIAGNOSIS_SUBTYPE", "masld_diagnosis_basis": "CL_MASLD_DIAGNOSIS_BASIS",
    "lymphoma_category": "CL_LYMPHOMA_CATEGORY", "cell_lineage": "CL_CELL_LINEAGE", "histologic_subtype": "CL_HISTOLOGIC_SUBTYPE", "diagnosis_status": "CL_DIAGNOSIS_STATUS",
}
# 필드별 타입 지정 (값 종류 휴리스틱을 덮어씀)
TYPE_OVERRIDE = {
    "clinical_tnm": ("varchar", r"^(y?c)?T(is|0|X|[1-4][a-c]?)N([0-3][a-c]?|X)M(0|1[a-c]?|X)$"), "pathologic_tnm": ("varchar", r"^(y?p)?T(is|0|X|[1-4][a-c]?)N([0-3][a-c]?|X)M(0|1[a-c]?|X)$"),
    "hvpg_mmhg": ("float", None), "gestational_diabetes_yn": ("integer", None), "age_at_diagnosis": ("integer", None), "diagnosis_name": ("varchar", None),
    "score_input_lab_name": ("varchar", None), "pft_item": ("varchar", None), "prognostic_score_value": ("float", None),
}
